<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // 6 Original Items (User Provided)
            [
                'seller_id' => 2,
                'name' => 'Jam Tangan Seiko 5 Automatic',
                'description' => 'Dijual jam tangan Seiko 5 dengan kondisi baru, pemakaian normal dan semua fungsi berjalan dengan baik. Tampilan masih rapi dengan strap stainless steel, cocok untuk dipakai harian maupun acara formal, kelengkapan fullset box dan surat, harga Rp 1.800.000, siap kirim dan nego tipis.',
                'price' => 1800000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Aksesoris',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Jaket Bomber Zara Men',
                'description' => 'Dijual jaket Zara model Bomber ukuran L dengan bahan polyester yang nyaman dipakai, kondisi preloved tanpa sobek atau noda, cocok untuk aktivitas harian maupun outdoor, warna masih solid dan layak pakai, harga Rp 450.000, siap kirim.',
                'price' => 450000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Fashion',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'iPhone 11 Pro 256GB',
                'description' => 'Dijual handphone iPhone 11 Pro kondisi preloved, pemakaian pribadi, semua fungsi normal, IMEI aman dan terdaftar, performa masih responsif untuk penggunaan sehari-hari, kelengkapan unit dan charger, minus lecet pemakaian wajar, harga Rp 5.500.000, bisa COD/rekber.',
                'price' => 5500000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Laptop ASUS ROG Zephyrus',
                'description' => 'Dijual laptop ASUS ROG Zephyrus kondisi preloved, performa masih sangat baik dan siap digunakan untuk kerja/kuliah/desain/gaming, fisik terawat dengan pemakaian wajar, baterai masih layak, kelengkapan charger dan box, harga Rp 15.000.000, siap kirim aman.',
                'price' => 15000000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Sepatu Nike Air Jordan 1',
                'description' => 'Dijual sepatu Nike Air Jordan 1 ukuran 43, kondisi baru, sol masih tebal dan nyaman dipakai, bahan masih bagus tanpa kerusakan berarti, cocok untuk harian/olahraga/fashion, harga Rp 2.300.000, siap kirim.',
                'price' => 2300000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Fashion',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Tas Kulit Fossil Messenger',
                'description' => 'Dijual tas kulit Fossil dengan bahan kulit asli, kondisi preloved dan masih sangat layak pakai, jahitan rapi dan resleting berfungsi normal, cocok untuk kerja maupun casual, harga Rp 1.500.000, siap kirim.',
                'price' => 1500000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Fashion',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 20 Additional Items (Generated)
            [
                'seller_id' => 2,
                'name' => 'Sony Alpha a6000 Mirrorless',
                'description' => 'Dijual kamera mirrorless Sony a6000 kit 16-50mm, kondisi mulus 95%, sensor bersih, fungsi normal 100%. Cocok untuk fotografi dan videografi pemula hingga pro. Kelengkapan fullset box, strap, charger. Harga Rp 5.200.000, nego bensin.',
                'price' => 5200000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'PlayStation 5 Disc Edition',
                'description' => 'Dijual konsol game PS5 garansi resmi Indonesia, kondisi baru segel (BNIB). Siap main game next-gen dengan grafis memukau 4K 120Hz. Kelengkapan fullset original. Harga Rp 8.500.000 nett.',
                'price' => 8500000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Sepeda Balap Polygon Strattos',
                'description' => 'Dijual road bike Polygon Strattos S2 ukuran M, frame alloy ringan, groupset Shimano Claris. Kondisi terawat, siap gowes jarak jauh. Lecet pemakaian wajar. Harga Rp 4.800.000, lokasi COD bisa diatur.',
                'price' => 4800000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Hobi & Olahraga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Gitar Akustik Yamaha F310',
                'description' => 'Dijual gitar akustik legend Yamaha F310 original. Suara nyaring dan jernih, action rendah nyaman dimainkan pemula. Kondisi body mulus, senar baru diganti. Bonus softcase. Harga Rp 950.000.',
                'price' => 950000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Hobi & Olahraga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Kursi Gaming Secretlab',
                'description' => 'Dijual gaming chair Secretlab Titan Evo 2022 SoftWeave. Kondisi bekas like new, busa masih sangat empuk, mekanisme tilt dan hydraulic normal. Sangat nyaman untuk duduk lama depan PC. Harga Rp 6.000.000, ambil sendiri lebih murah.',
                'price' => 6000000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Rumah Tangga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Kemeja Flannel Uniqlo L',
                'description' => 'Dijual kemeja flannel Uniqlo original size L. Motif kotak-kotak merah hitam klasik. Kondisi 90%, warna masih pekat tidak pudar, kancing lengkap. Nyaman dipakai casual. Harga Rp 150.000.',
                'price' => 150000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Fashion',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Apple iPad Air 5 M1',
                'description' => 'Dijual iPad Air 5 chip M1 64GB WiFi Only. Performa ngebut setara MacBook, cocok untuk editing video atau ilustrasi. Kondisi fisik mulus, baterai awet. Kelengkapan unit dan charger original. Harga Rp 8.200.000.',
                'price' => 8200000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Action Figure Gundam MG Barbatos',
                'description' => 'Dijual model kit Gundam MG 1/100 Barbatos sudah dirakit (built). Decal sudah pasang rapi, lining tipis. Sendi masih seret, part lengkap dengan dus dan manual. Cocok untuk pajangan. Harga Rp 650.000.',
                'price' => 650000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Hobi & Olahraga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Smart TV Samsung 43 Inch 4K',
                'description' => 'Dijual Samsung UHD 4K Smart TV 43 inch seri AU7000. Gambar tajam kristal, support Netflix, YouTube, Disney+. Kondisi normal, remote ada, kaki TV ada. Dus sudah tidak ada. Harga Rp 3.500.000.',
                'price' => 3500000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Headphone Sony WH-1000XM4',
                'description' => 'Dijual headphone noise cancelling terbaik Sony WH-1000XM4. Suara detail, bass empuk, fitur ANC kedap suara luar biasa. Baterai tahan 30 jam. Kondisi 98% mulus, jarang pakai. Harga Rp 2.900.000.',
                'price' => 2900000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Meja Kerja Minimalis Ikea',
                'description' => 'Dijual meja kerja/belajar model minimalis ala Ikea LINNMON. Warna putih bersih, ukuran 100x60cm. Kondisi masih kokoh, ada sedikit noda tinta di permukaan tapi tidak mengganggu fungsi. Harga Rp 400.000.',
                'price' => 400000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Rumah Tangga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Drone DJI Mini 2 SE',
                'description' => 'Dijual drone DJI Mini 2 SE Fly More Combo. Kamera 2.7K stabil dengan gimbal 3-axis. Cocok untuk travel vlogger. Kondisi baru buka dus (BNOB), belum pernah terbang. Baterai 3 buah, tas, remote lengkap. Harga Rp 5.800.000.',
                'price' => 5800000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Hobi & Olahraga',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Novel Harry Potter',
                'description' => 'Dijual koleksi novel Harry Potter. Kondisi kertas agak menguning wajar karena usia, tapi halaman lengkap tidak ada yang sobek. Bonus box set custom. Harga Rp 750.000.',
                'price' => 750000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1663953322505-1238f663ede1?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Hobi & Olahraga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Skateboard Fullset Element',
                'description' => 'Dijual skateboard fullset deck Element, trucks Independent, wheels Spitfire. Setup mantap untuk street skating. Kondisi lecet pemakaian wajar di tail dan nose, bearing masih loncer. Harga Rp 1.200.000.',
                'price' => 1200000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1422000670866-529d53611fe9?q=80&w=1162&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Hobi & Olahraga',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Kopi Arabika Gayo 1kg',
                'description' => 'Dijual biji kopi (roasted bean) Arabika Aceh Gayo grade 1, kemasan 1kg. Profil roasting medium to dark, cocok untuk espresso atau tubruk. Aroma kuat, body tebal, acidity rendah. Fresh roast. Harga Rp 180.000.',
                'price' => 180000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Makanan & Minuman',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Powerbank Anker 20000mAh',
                'description' => 'Dijual powerbank Anker PowerCore 20000mAh support fast charging PD 20W. Bisa cas iPhone hingga 50% dalam 30 menit. Kapasitas real, aman dibawa ke pesawat. Kondisi mulus, fungsi normal. Harga Rp 450.000.',
                'price' => 450000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1745888050708-b6136ce7fde3?q=80&w=1073&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Aksesoris',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Vacuum Cleaner Robot Xiaomi',
                'description' => 'Dijual robot vacuum Xiaomi Mi Robot Vacuum-Mop 2 Lite. Bisa sapu dan pel sekaligus, navigasi pintar hindari rintangan. Bisa dikontrol lewat HP. Kondisi 90%, filter cadangan masih ada. Harga Rp 1.900.000.',
                'price' => 1900000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1722710070534-e31f0290d8de?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Helm Kyt NFR Full Face',
                'description' => 'Dijual helm full face KYT NFR motif Espargaro, size L. Visor flat clear, sudah ada slot intercom. Busa tebal dan wanginy masih enak. Mulus, belum pernah jatuh. Kelengkapan sarung helm. Harga Rp 1.600.000.',
                'price' => 1600000,
                'stock_quantity' => 10,
                'image' => 'https://plus.unsplash.com/premium_photo-1663050993391-c1267353cab5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Otomotif',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'name' => 'Tanaman Hias Monstera King',
                'description' => 'Dijual tanaman hias Monstera Deliciosa King (Janda Bolong), daun sudah pecah rimbun, tinggi sekitar 60cm. Sudah termasuk pot terakota cantik. Cocok untuk dekorasi indoor/outdoor. Harga Rp 250.000.',
                'price' => 250000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=1000&auto=format&fit=crop',
                'category' => 'Rumah Tangga',
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'name' => 'Mesin Cuci Samsung Top Load',
                'description' => 'Dijual mesin cuci Samsung bukaan atas (Top Load) kapasitas 8kg. Teknologi Wobble menjaga pakaian tidak melilit. Hemat listrik dan air. Kondisi normal pemakaian 1 tahun. Alasan jual mau pindah luar kota. Harga Rp 2.100.000.',
                'price' => 2100000,
                'stock_quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1662220984920-3bd1f88e846f?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'category' => 'Elektronik',
                'condition' => 'used',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}